modLoader = "kotlinforforge"
loaderVersion = "[4.3.0,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "blue_archive_halo"
version = "${version}-forge"
displayName = "Blue Archive Halo"
authors = "2894638479"
description = '''
仿碧蓝档案光环。支持多数光影，有配置页面
'''
logoFile = "assets/blue-archive-halo/icon.png"


[[dependencies.blue_archive_halo]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blue_archive_halo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blue_archive_halo]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"